#!/usr/bin/env bash
#  A Bash script that transfers a file from our client
#+ to a server using scp

if [ $# -ge 3 ]
then
    PATH_TO_SSH_KEY=$4
    PATH_TO_FILE=$1
    USERNAME=$3
    IP=$2
    scp -o StrictHostKeyChecking=no -i \
         "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME"@"$IP":~/
else
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
