#!/usr/bin/env bash
#  A Bash Script that installs and configures
#+ an nginx server

echo "Initiating installation and web server start-up..."
# update and install nginx
apt -y update
apt install -y nginx


# adjust ufw
ufw allow 'Nginx HTTP'

# start nginx service
service nginx start

echo "Configuring web server to serve files..."
# create index page with string
echo "Hello World!" > /var/www/html/index.html
# ensure serving on port 80
#sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sed -i 's/^\tlisten\s[[:digit:]]\+\s/\tlisten 80 /g' /etc/nginx/sites-enabled/default

sed -i 's/^\tlisten\s\[::\]:[[:digit:]]\+\s/\tlisten [::]:80 /g' /etc/nginx/sites-enabled/default

service nginx restart
